version: "3.1"

# username, pwd 설정 시 studio 3T에서 접근이 안됨
services:
  mongodb-study:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
